on:
  push:
    branches:
    - main
    tags:
    - 'v*'

name: Release policy

jobs:

  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-rust.yml@v2

  release:
    needs: test
    permissions:
      # Required to push to GHCR
      contents: write
      packages: write
      # Required by cosign keyless signing
      id-token: write

    uses: kubewarden/github-actions/.github/workflows/reusable-release-policy-rust.yml@v2
    with:
      input-wasm: seccomp_psp_policy
      oci-target: ghcr.io/${{ github.repository_owner }}/policies/seccomp-psp
